common_args:
  training_type: "simulation"
  random_seed: 0

config_version: release

data_args:
  dataset: "mnist"
  data_cache_dir: ~/.cache/fedml_data
  partition_method: "hetero"       # Non-IID (label skew)
  partition_alpha: 0.5             # Lower = more bias

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 50          # ⬅️ Simulate 50 clients
  client_num_per_round: 10         # ⬅️ Train on 10 clients per round
  comm_round: 20                   # ⬅️ More rounds = better convergence
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1         # Test every round

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  enable_tracking: false
  enable_wandb: false
  log_file_dir: ./log
  run_name: fedml_torch_fedavg_mnist_lr
  mlops_api_key: c9356b9c4ce44363bb66366b210201
  mlops_project_name: alex-test-prj
  mlops_run_name: fedml_torch_fedavg_mnist_lr_2
